### ISSUE TITLE
org.jboss.modules.ModuleNotFoundException: com.squareup.okhttp3

### ISSUE THREAD

**Issue by awsmaythem** [jboss-dockerfiles/wildfly#160]
Hello
Am using Redhat SSO 7.6 image docker
when i run docker image the "PrivacyIDEA-Provider.jar" failed to load module
am using "PrivacyIDEA-Provider-v1.1.0.jar" and copy it in the image at location "/opt/eap/standalone/deployments/"
and the directory providers not found in default image,
the service is running but no privacyidea module.
here is the log error:
```
ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.module.service."deployment.PrivacyIDEA-Provider.jar".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.PrivacyIDEA-Provider.jar".main: WFLYSRV0179: Failed to load module: deployment.PrivacyIDEA-Provider.jar
        at org.jboss.as.server@15.0.8.Final-redhat-00001//org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:116)
        at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jboss.modules.ModuleNotFoundException: com.squareup.okhttp3
        at org.jboss.modules.Module.addPaths(Module.java:1288)
        at org.jboss.modules.Module.link(Module.java:1644)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1672)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:303)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:287)
        at org.jboss.as.server@15.0.8.Final-redhat-00001//org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:93)
        ... 8 more

ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "PrivacyIDEA-Provider.jar")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.module.service.\"deployment.PrivacyIDEA-Provider.jar\".main" => "WFLYSRV0179: Failed to load module: deployment.PrivacyIDEA-Provider.jar
    Caused by: org.jboss.modules.ModuleNotFoundException: com.squareup.okhttp3"}}
ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Core 15.0.8.Final-redhat-00001 started (with errors) in 19991ms - Started 729 of 1091 services (2 services failed or missing dependencies, 771 services are lazy, passive or on-demand)
```
i know it need "com.squareup.okhttp3" so i add it:
```
COPY okhttp-3.14.9.redhat-00001.jar /opt/eap/standalone/deployments/okhttp-3.14.9.redhat-00001.jar
```
still the same error.

**Comment by awsmaythem** [comment]
Redhat SSO 7.6
<html><body>


Component | Version
-- | --
Keycloak | 18.0.0


</body>
</html>
