### ISSUE TITLE
Fix permisssions to be able to run the image on OpenShift with random user

### ISSUE THREAD

**Issue by jorgemoralespou** [jboss-dockerfiles/wildfly#25]
Currently, provided the permissions set for /opt/jboss the image does not work on an OpenShift installation OOTB with a restricted SCC (the default). We should change permissions to this (and maybe base) images so that this image can be deployed on OpenSHift OOTB without modifications.

**Comment by goldmann** [comment]
Sure, this makes sense, but I don't see any PR attached :P

**Comment by jorgemoralespou** [comment]
If I just was sure what would be best way, would make the PR. but not sure. you tell me, I'll code. Otherwise, you choose. 😉

**Comment by goldmann** [comment]
Hmm, wait a sec :) Are you talking about basically chmodding 777 files that could be touched/modified by the user running this particular image? If this is the case, I'm -1 for the idea making part of this image.

**Comment by jorgemoralespou** [comment]
why?

**Comment by l-d-j** [comment]
These images are considered general purpose - not OpenShift flavored. 
Also I think, that effective UID should *not* be able to modify any binaries it runs - also world-writable directories are considered a bad pattern in a UNIX/Linux world and we still have OS inside our containers (hope some project will find a way *ideally* to ship one static binary and its data in future). Image also lacks a lot of other stuff like s2i,jolika, etc and I prefer not to see any PR/Issues for OpenShift requirements/goodness :) in this images
I would prefer to use this image as upstream and let OpenShift project own/provide changes.(I can volunteer for it)

**Comment by goldmann** [comment]
In fact they already provide OpenShift WildFly image: https://github.com/openshift/sti-wildfly

**Comment by goldmann** [comment]
And just to be clear, I agree with @l-d-j with all the points.

**Comment by jorgemoralespou** [comment]
@marek that is s2i image and that's different story. 
as with any image, a user would love to be able to run s2i images or just plain old instead where they would layer their app. 
I agree about the bad patterns that world writable directories ate in Linux, but until we have user namespaces in kernel this is just not going to work. 
Is we want people to use this images in an openshift world, which we should do, we would need to hack this images for the time being, or explain users how they should hack them, which I see from your comments to be preferred. 
thanks for clarifying direction of these images.

**Comment by lionelve** [comment]
@jorgemoralespou can you tell me what's the hack to make this work in openshift. tx.

**Comment by vnugent** [comment]
I'm also interested in running WF in OpenShift v3.   For some reason uid is no longer 1000 .

```
sh-4.2$ id                                                                      
uid=1000060000 gid=0(root) groups=0(root),1000060000                            
sh-4.2$ whoami                                                                  
whoami: cannot find name for user ID 1000060000  
```

server log:

```
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /opt/jboss/wildfly

  JAVA: /usr/lib/jvm/java/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

java.lang.IllegalArgumentException: Failed to instantiate class "org.jboss.logmanager.handlers.PeriodicRotatingFileHandler" for handler "FILE"
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:116)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.doPrepare(LogContextConfigurationImpl.java:335)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.prepare(LogContextConfigurationImpl.java:288)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.commit(LogContextConfigurationImpl.java:297)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:546)
	at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:97)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:514)
	at org.jboss.logmanager.LogManager.readConfiguration(LogManager.java:476)
	at java.util.logging.LogManager$3.run(LogManager.java:399)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at org.jboss.modules.Main.main(Main.java:482)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ConstructAction.validate(AbstractPropertyConfiguration.java:114)
	... 17 more
Caused by: java.io.FileNotFoundException: /opt/jboss/wildfly/standalone/log/server.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:151)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:102)
	at org.jboss.logmanager.handlers.FileHandler.setFileName(FileHandler.java:189)
	at org.jboss.logmanager.handlers.FileHandler.<init>(FileHandler.java:119)
	at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.<init>(PeriodicRotatingFileHandler.java:70)
	... 22 more
java.lang.IllegalStateException: WFLYSRV0124: Could not create server data directory: /opt/jboss/wildfly/standalone/data
	at org.jboss.as.server.ServerEnvironment.<init>(ServerEnvironment.java:473)
	at org.jboss.as.server.Main.determineEnvironment(Main.java:297)
	at org.jboss.as.server.Main.main(Main.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.modules.Module.run(Module.java:329)
at org.jboss.modules.Main.main(Main.java:507)
```

**Comment by vnugent** [comment]
I figured out what the problem was (PR to follow). OpenShift assigns a random user to to run the container. Hence the file permission error.  According OpenShift [docker guidelines](https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines)  jboss dir needs to have root group permissions.  The following additions enable wildfly to run:

```
...
USER root
RUN chgrp -R 0 $JBOSS_HOME &&\
chmod -R g+rw $JBOSS_HOME
...
```

**Comment by goldmann** [comment]
Referenced PR was merged, closing this issue.
