### ISSUE TITLE
Unable to mount the volume for deployment

### ISSUE THREAD

**Issue by log-test** [jboss-dockerfiles/wildfly#57]
I am trying to mount the deployment folder for docket using docker base image but getting the following error as unable to write. The following command that I run. 

Is this something can be included in the base image to fix this issue ?

**docker run -it  -v /d/babu/installas/deployment:/opt/jboss/wildfly/standalone/deployments/:rw jboss/wildfly**

017-06-21T09:32:02.746464536Z =========================================================================
2017-06-21T09:32:02.746469025Z 
2017-06-21T09:32:03.569869835Z [0m09:32:03,567 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
2017-06-21T09:32:04.155922174Z [0m[0m09:32:04,155 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
2017-06-21T09:32:04.256966545Z [0m[0m09:32:04,255 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) starting
2017-06-21T09:32:06.585219569Z [0m[31m09:32:06,583 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 6) WFLYCTL0013: Operation ("add") failed - address: ([
2017-06-21T09:32:06.585273931Z     ("subsystem" => "deployment-scanner"),
2017-06-21T09:32:06.585278567Z     ("scanner" => "default")
2017-06-21T09:32:06.585281418Z ]): java.lang.IllegalArgumentException: WFLYDS0024: /opt/jboss/wildfly/standalone/deployments is not writable
2017-06-21T09:32:06.585284035Z 	at org.jboss.as.server.deployment.scanner.FileSystemDeploymentService.<init>(FileSystemDeploymentService.java:279)
2017-06-21T09:32:06.585286804Z 	at org.jboss.as.server.deployment.scanner.DeploymentScannerAdd.execute(DeploymentScannerAdd.java:124)
2017-06-21T09:32:06.585289326Z 	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
2017-06-21T09:32:06.585291962Z 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
2017-06-21T09:32:06.585294551Z 	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
2017-06-21T09:32:06.585297157Z 	at org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:359) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
2017-06-21T09:32:06.585299845Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_131]
2017-06-21T09:32:06.585302363Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_131]
2017-06-21T09:32:06.585311064Z 	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_131]
2017-06-21T09:32:06.585313972Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:320) [jboss-threads-2.2.1.Final.jar:2.2.1.Final]
2017-06-21T09:32:06.585316552Z 
2017-06-21T09:32:06.696214701Z [0m[31m09:32:06,695 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) "WFLYCTL0193: Failed executing subsystem deployment-scanner boot operations"
2017-06-21T09:32:06.698226894Z [0m[31m09:32:06,697 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-subsystem-boot") failed - address: ([]) - failure description: "\"WFLYCTL0193: Failed executing subsystem deployment-scanner boot operations\""

**Comment by log-test** [comment]
It works by adding the following. Thanks.
USER root
RUN chown jboss:jboss /opt/jboss/wildfly/standalone/deployments/*
