### ISSUE TITLE
Error saving standalone.xml on mapped config file

### ISSUE THREAD

**Issue by BenPru** [jboss-dockerfiles/wildfly#70]
I create the wildfly container with mapping the standalone.xml config file from outsige into the container.
For example:
docker run ... -v standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml

Now I make changes in the admin interface in the wildfly. But the wildfly can't save the changes!
Internal the wildfly saves the changes to a new file and delete the original standalone.xml and move the new one to /opt/jboss/wildfly/standalone/configuration/standalone.xml.
But this is not allowed for mapped files.
Please fix this.

Error message:
2018-01-09 14:12:21,469 ERROR [org.jboss.as.controller.management-operation] (External Management Request Threads -- 2) org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0268: Fai
led to rename temp file /opt/jboss/wildfly/standalone/configuration/standalone.xml.tmp to /opt/jboss/wildfly/standalone/configuration/standalone.xml: org.jboss.as.controller.persistence.ConfigurationPersiste
nceException: WFLYCTL0268: Failed to rename temp file /opt/jboss/wildfly/standalone/configuration/standalone.xml.tmp to /opt/jboss/wildfly/standalone/configuration/standalone.xml
        at org.jboss.as.controller.persistence.FilePersistenceUtils.moveTempFileToMain(FilePersistenceUtils.java:82)
        at org.jboss.as.controller.persistence.ConfigurationFile.commitTempFile(ConfigurationFile.java:541)
        at org.jboss.as.controller.persistence.ConfigurationFilePersistenceResource.doCommit(ConfigurationFilePersistenceResource.java:63)
        at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.commit(AbstractFilePersistenceResource.java:58)
        at org.jboss.as.controller.ModelControllerImpl$4.commit(ModelControllerImpl.java:789)
        at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:743)
        at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:680)
        at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
        at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
        at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:400)
        at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:222)
        at org.jboss.as.domain.http.server.DomainApiHandler.handleRequest(DomainApiHandler.java:219)
        at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(EncodingHandler.java:72)
        at org.jboss.as.domain.http.server.security.SubjectDoAsHandler$1.run(SubjectDoAsHandler.java:72)
        at org.jboss.as.domain.http.server.security.SubjectDoAsHandler$1.run(SubjectDoAsHandler.java:68)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:149)
        at org.jboss.as.domain.http.server.security.SubjectDoAsHandler.handleRequest(SubjectDoAsHandler.java:68)
        at org.jboss.as.domain.http.server.security.SubjectDoAsHandler.handleRequest(SubjectDoAsHandler.java:63)
        at io.undertow.server.handlers.BlockingHandler.handleRequest(BlockingHandler.java:56)
        at org.jboss.as.domain.http.server.DomainApiCheckHandler.handleRequest(DomainApiCheckHandler.java:95)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.nio.file.FileSystemException: /opt/jboss/wildfly/standalone/configuration/standalone.xml: Device or resource busy
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
        at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
        at java.nio.file.Files.move(Files.java:1395)
        at org.jboss.as.controller.persistence.FilePersistenceUtils.moveTempFileToMain(FilePersistenceUtils.java:80)
        ... 27 more

**Comment by BenPru** [comment]
Hello, can anyone help me?

**Comment by Lone1567** [comment]
Any update on this?

**Comment by didlich** [comment]
I've tested it with WF17 and WF18 on Ubuntu 18.04 with docker

```
Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 185
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
```

, the problem is still there.
The only workaround is to map the complete "standalone/configuration" directory.

What need to be fixed in wildfly to allow this kind of mapping?

Regards.

**Comment by softshipper** [comment]
I have also the same problem.

Thanks

**Comment by zwessels** [comment]
The problem goes away if you copy the file into the docker container rather than to mount it as a volume. I suspect the problem is permissions as pointed out by @goldmann. 

Seems to be a long running issue with Docker: https://github.com/moby/moby/issues/2259

**Comment by slominskir** [comment]
This is not a permissions issue.  This is due to mounting the standalone.xml file itself instead of the directory containing it.   If you mount a single file in docker then you can't delete or move that file else Docker get's confused.  Wildfly apparently likes to move/delete/replace that file with "standalone.xml.tmp" occasionally.   Docker usually stops you from deleting or moving the file used as a mount with the following error: 
```
java.nio.file.FileSystemException: /opt/jboss/wildfly/standalone/configuration/standalone.xml: Device or resource busy
```

As already mentioned, the workaround is to mount the parent configuration directory instead.  This is not optimal because it means you must provide all the other files in the configurations directory now too.
